### ISSUE TITLE
We need to change our naming convention -> accidental S3 methods

### ISSUE THREAD

**Issue by bw4sz** [TheoreticalEcosystemEcology/alienR#15]
I think we are accidentally creating S3 export methods (i.e a predict generic class), by mistake. I noticed that.

For example, the function cannot be called, but is exported and documented.
```
library(alienR) 
> library(alienR)
> predict.bayesreg
Error: object 'predict.bayesreg' not found
> ?predict.bayesreg
```
works fine.
http://r-pkgs.had.co.nz/man.html

see Documenting classes, generics and methods.
I think what is happening is predict.bayesreg is a predict generic function for a class bayesreg. I do not know how to set a class, or whether output objects automatically have classes? I suggest we just change all functions from . to _ . For example, predict.bayesreg becomes predict_bayesreg

**Comment by bw4sz** [comment]
playing around with @exportClass tag in the roxygen docs.

**Comment by bw4sz** [comment]
I changed my names, as part of pull request #11

**Comment by SteveViss** [comment]
Hi @bw4sz,

Functions and object names convention are written in the README. Have a look at the first and second bullet points in styleguide section:

- function names are explicit and with CamelCased verbs, e.g. SimulatesNicheModel.
- objects are declared with lowercase, underscores and small caps, e.g. trophic_level

I'll change tomorrow all the names already declared in the package according to these.
Cheers,
Steve

**Comment by bw4sz** [comment]
Looks like steve took care of this.
