### ISSUE TITLE
Package name??

### ISSUE THREAD

**Issue by tpoisot** [TheoreticalEcosystemEcology/alienR#4]
Please? Can we discuss this? I believe this is a terrible name.

**Comment by KevCaz** [comment]
Personally, I like the acronym. It's a good combination of keywords as well as a reference to one  major goal of the methods implemented: predicting the links an alien species could experience when colonizing a new area. However I understand that one cannot guess what the package does based on this name.

**Comment by tpoisot** [comment]
I think it's a good *codename* for us, but a bad package name.

1. It's not descriptive
2. It's not obvious from the name what it does
3. It has a `R` at the end for no reason

**Comment by SteveViss** [comment]
@tpoisot, your arguments are valuable. If you have new names in mind write them in this issue. Then if needed, we can discuss them and take a final decision at the next meeting. We had to find a repo name and we found this one attractive. `predNet` and `predLink` were two other propositions that emerge from the workshop.

At this stage, I think nothing is definitive and honestly the members of the workshop were more focused on coding and merging methods than finding an explicit name.

**Comment by KevCaz** [comment]
I have a new proposition if we decide to change the : **inferaction**

**Comment by SteveViss** [comment]
Proposition by Dom: infernet
And @tpoisot, the capital R at the end will be remove for sure.

**Comment by SteveViss** [comment]
Ok, we keep `alien` as the official name. At the first release to the CRAN, we can have a second chat on this topic. I close temporary this issue.
