### ISSUE TITLE
explicit name space or @import 

### ISSUE THREAD

**Issue by KevCaz** [TheoreticalEcosystemEcology/alienR#7]
When calling a function from another package in one of our own function, should we:

1- use explicit spacename, *e.g* `reshape2::acast` 
2- using `@importFrom reshape2 acast`when documenting the function (using Roxygen) 
3- or both?

Whatever our choice, I think it should be consistent throughout the code.

**Comment by bw4sz** [comment]
A bit old, but the roxygen2 package developer suggests the first option. Is this still true?

see [here](http://stackoverflow.com/questions/8597993/does-roxygen2-automatically-write-namespace-directives-for-imports-packages)

**Comment by KevCaz** [comment]
I agree we should use the first one as recommended by Hadley Wickham who also suggests the use of `@importFrom` (or other kind of import) in particular case such as S3 object / methods / pipes (%>%).

**Comment by SteveViss** [comment]
Works for me!
